### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by InstantlyMoist** [nopjmp/Dionysus#132]
When building from the clone, it simply does not work. I have java 8 installed. 

Downloading unmapped vanilla jar...
Applying class mappings...
Applying member mappings...
Exception in thread "main" java.util.zip.ZipException: zip END header not found
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:347)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:318)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:284)
        at net.md_5.ss.SpecialSource.map(SpecialSource.java:69)
        at net.md_5.ss.SpecialSource.main(SpecialSource.java:44)
Failed to build Paper
scripts/upstream.sh: line 43: cd: Paper-Server: No such file or directory

**Comment by RaymanoPL** [comment]
Set java 8
./dionysus patch
Set java 17
Run ./dionysus build
